CREATE TABLE IF NOT EXISTS "user" (
  id VARCHAR PRIMARY KEY NOT NULL,
  name VARCHAR NOT NULL,
  nis INT NOT NULL,
  passphrase VARCHAR NOT NULL,
  email VARCHAR NOT NULL,
  no_telp VARCHAR NOT NULL,
  gender VARCHAR NOT NULL,
  religion VARCHAR NOT NULL
);